name: Ella Mizuki
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, synchronize]
  workflow_run:
    workflows: ["*"]
    types: [completed]

jobs:
  ella:
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.name != 'Ella Mizuki') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/ella') && github.event.comment.user.login == github.repository_owner) ||
      (github.event_name == 'issues' && github.event.action == 'opened') ||
      (github.event_name == 'pull_request_target' && (github.event.action == 'opened' || github.event.action == 'synchronize'))
    runs-on: ubuntu-latest
    env:
      ELLA_AI_API_KEY: ${{ secrets.ELLA_AI_API_KEY }}
      ELLA_AI_BASE_URL: ${{ secrets.ELLA_AI_BASE_URL }}
      ELLA_AI_MODEL: ${{ secrets.ELLA_AI_MODEL }}
    steps:
      - name: Chamando a Ella
        uses: isyuricunha/ella@main
        with:
          ella_app_client_id: ${{ secrets.ELLA_APP_CLIENT_ID }}
          ella_app_private_key: ${{ secrets.ELLA_APP_PRIVATE_KEY }}
